### PR TITLE
Add Prometheus, Grafana, asbench

### PR DESCRIPTION
**Pull request by sourabh3b**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sourabh3b** [comment]
@Klaven this PR has temporary changes, please take a look

**Comment by sourabh3b** [comment]
@gargana @troy-ameigh can you please help me fix some of the linting issues ? I've fixed '*' action issues but that added '*' resource issues.

**Comment by sourabh3b** [comment]
@gargana @troy-ameigh please take a look at the PR, thanks

**Review by gargana — APPROVED** [review]
LGTM - Shipping

**Comment by gargana** [comment]
Merging.

**Pull request merged**
